import { GoogleGenAI, Modality, Chat, GenerateContentResponse } from "@google/genai";
import { GroundingChunk } from "../types";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });
const imageGenerationModel = 'gemini-2.5-flash-image';
const groundingModel = 'gemini-2.5-flash';

// Cached chat instance
let chat: Chat | null = null;

const getChat = () => {
    if (!chat) {
        chat = ai.chats.create({
            model: groundingModel,
            config: {
                systemInstruction: "You are a helpful AI assistant for the Smile Reborn app. Answer questions about dental health, cosmetic procedures, and financing options. Be encouraging and clear. Your goal is to help users on their journey to a better smile."
            }
        });
    }
    return chat;
}

export const generatePerfectSmile = async (base64Image: string, mimeType: string): Promise<string> => {
  try {
    const prompt = `Given this image of a person's teeth, generate a new image showing a perfect, healthy, and brilliant smile. The generated smile should look natural and realistic for the person. Correct issues like discoloration, gaps, misalignment, and gum health to create an aspirational yet achievable result. Do not change the rest of the person's face or the background.`;

    const response = await ai.models.generateContent({
      model: imageGenerationModel,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const generatedPart = response.candidates?.[0]?.content?.parts?.[0];
    if (generatedPart && generatedPart.inlineData) {
      return generatedPart.inlineData.data;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating smile:", error);
    throw new Error("Failed to generate the smile transformation. Please try again.");
  }
};

export const findNearbyDentistsByCoords = async (latitude: number, longitude: number): Promise<{ text: string, sources: GroundingChunk[] }> => {
  try {
    const prompt = `Based on my current location, find the top-rated cosmetic dentists physically closest to me who are experts in smile makeovers, veneers, and implants. Please provide a list including their name, full address, and contact information if available.`;
    
    const response = await ai.models.generateContent({
      model: groundingModel,
      contents: prompt,
      config: {
        tools: [{ googleMaps: {} }],
        toolConfig: {
          retrievalConfig: {
            latLng: {
              latitude: latitude,
              longitude: longitude,
            }
          }
        }
      },
    });

    const text = response.text;
    const sources = response.candidates?.[0]?.groundingMetadata?.groundingChunks ?? [];
    return { text, sources };
  } catch (error) {
    console.error("Error finding dentists:", error);
    throw new Error("Failed to find nearby dentists. Please check your connection and try again.");
  }
};

export const findNearbyDentistsByQuery = async (locationQuery: string): Promise<{ text: string, sources: GroundingChunk[] }> => {
  try {
    const prompt = `Based on the location "${locationQuery}", find the top-rated cosmetic dentists physically closest to that area who are experts in smile makeovers, veneers, and implants. Please provide a list including their name, full address, and contact information if available.`;
    
    const response = await ai.models.generateContent({
      model: groundingModel,
      contents: prompt,
      config: {
        tools: [{ googleMaps: {} }],
      },
    });

    const text = response.text;
    const sources = response.candidates?.[0]?.groundingMetadata?.groundingChunks ?? [];
    return { text, sources };
  } catch (error) {
    console.error("Error finding dentists:", error);
    throw new Error("Failed to find nearby dentists. Please check your connection and try again.");
  }
};

export const getFinancingOptionsByCoords = async (latitude: number, longitude: number): Promise<{ text: string, sources: GroundingChunk[] }> => {
  try {
    const prompt = `Find dental financing options available for someone at my location. Include details about major national providers like CareCredit and LendingPoint. Also, find specific dental practices near my location that offer their own in-house financing or payment plans. Provide a summary of the options, what they cover, and how to apply.`;
    
    const response = await ai.models.generateContent({
      model: groundingModel,
      contents: prompt,
      config: {
        tools: [{ googleSearch: {} }, { googleMaps: {} }],
        toolConfig: {
          retrievalConfig: {
            latLng: {
              latitude,
              longitude,
            },
          },
        },
      },
    });

    const text = response.text;
    const sources = response.candidates?.[0]?.groundingMetadata?.groundingChunks ?? [];
    return { text, sources };
  } catch (error) {
    console.error("Error getting financing options:", error);
    throw new Error("Failed to find financing options. Please check your connection and try again.");
  }
};

export const getFinancingOptionsByQuery = async (locationQuery: string): Promise<{ text: string, sources: GroundingChunk[] }> => {
  try {
    const prompt = `Find dental financing options available for someone in "${locationQuery}". Include details about major national providers like CareCredit and LendingPoint. Also, find specific dental practices near that location that offer their own in-house financing or payment plans. Provide a summary of the options, what they cover, and how to apply.`;
    
    const response = await ai.models.generateContent({
      model: groundingModel,
      contents: prompt,
      config: {
        tools: [{ googleSearch: {} }, { googleMaps: {} }],
      },
    });

    const text = response.text;
    const sources = response.candidates?.[0]?.groundingMetadata?.groundingChunks ?? [];
    return { text, sources };
  } catch (error) {
    console.error("Error getting financing options:", error);
    throw new Error("Failed to find financing options. Please check your connection and try again.");
  }
};

export const sendMessageToBot = async (message: string): Promise<string> => {
    try {
        const chatSession = getChat();
        const response = await chatSession.sendMessage({ message });
        return response.text;
    } catch (error) {
        console.error("Error in chatbot:", error);
        throw new Error("The chatbot is currently unavailable. Please try again later.");
    }
};